GET http://localhost:3000/auth/users

###

POST https://www.yuksecurity.com/api/auth/register
Content-Type: application/json

    {
        "email": "losaruby@gmail.com",
        "username": "losaruby",
        "password": "loser"
    }

###
POST https://www.yuksecurity.com/api/auth/verifyregistry?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imxvc2FydWJ5QGdtYWlsLmNvbSIsInVzZXJuYW1lIjoibG9zYXJ1YnkiLCJwYXNzd29yZCI6IiQyYiQxMCRvVWVWUGc4ODM4VUtpMEl6MGUuaGZ1SjRzaW9OVGtZMU5ldGxDV0RYbkR1c2c0L1VJVXdXRyIsImlhdCI6MTY2MTAwMDQ5MywiZXhwIjoxNjYxMDAwNzkzfQ.MkHiiSMtSYhSsil2w_Y225vm-ALPMN7Z_0bjWQMFbBE


###

POST https://www.yuksecurity.com/api/auth/login
Content-Type: application/json

    {
        "username": "losaruby",
        "password": "loser",
        "recaptcha_token": "03AD1IbLBsykUm7Ac8Od6rJ7hY4bAnikUqUgc1KUnp0aL14BahcEtc9By5VMMYIQk_Ei6rEVqudcK9mkxq3Lz29uGKXvaBHkJpjOmNzJ47bk7mie24lnKtK-XQnMKQAw1U9JdoIqg6jpvTa3-S4k1AmtssDLJOeiQ-pSVYhdOWl3a9ZlmDDW0a5zuWbya6iFm3Rf-HEf8wPHjFRmHnBehDztRSooCSqlqlPLszxfpnLnfmKXb-SVQomn_HF-aMsZ-xzVUqYU4e7GcPIpDbYrNnG0rC5-II-MG4xmqruZ35ip7wYiUXmiU0KG-n3_9XqFaAEklMyrlilN0CVlWXG9sGtNT1yUV4vjxsadz9plcqwOQJ-EMhLwSPzWnGNYn6NQU_nDx-zDvzHguCfejxBCQdlUBg5sjWMT8WD-y3uxVOFs_17oxqyvkJI2Q-HsccD28xhhdNxzqmXQq1jeTXcuZZwOMTXW8LicPtjp7SdUH5zbrs7JDaGSZEMJivNp9pwKHO7Ue314IV8wjqPGuqyM4irP6OPejuSBqtc9-5RJz4mV2zUwVZcg5aAxsetsp3We0YWftLvAlr9Np_xrywiuDh9B-15cy6ADKfkg"

    }

###
GET https://www.yuksecurity.com/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTk3ODIwMDksImV4cCI6MTY1OTc4MjMwOX0.VK7JCkRBw0mDCRbCBiJ2KIj5MO9th5WpukIiOqshpsA
Content-Type: application/json

###
POST https://www.yuksecurity.com/api/auth/refresh
Content-Type: application/json
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIiLCJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE2NjA3OTg5ODQsImV4cCI6MTY2MDgwMjU4NH0.ntaqPb_s-VxBxTHQyY40MYR_Pde4Vk4gfohO6SnQ44M

###
GET http://localhost:3500/accounts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIiLCJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE2NjAxMjM0ODIsImV4cCI6MTY2MDEyMzc4Mn0.vss7USi-WaEx1QPFRO7B78-PILz_fs0OAuz7AXqkF6U
Content-Type: application/json

###
POST http://localhost:3500/accounts/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIiLCJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE2NjAxMjM0ODIsImV4cCI6MTY2MDEyMzc4Mn0.vss7USi-WaEx1QPFRO7B78-PILz_fs0OAuz7AXqkF6U
Content-Type: application/json






