GET http://localhost:3000/auth/users

###

POST http://localhost:3000/auth/register
Content-Type: application/json

    {
        "email": "test@test.com",
        "username": "test",
        "password": "test"
    }

###

POST http://localhost:4000/api/auth/login
Content-Type: application/json

    {
        "username": "test",
        "password": "test"
    }

###
GET http://localhost:4000/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTk3ODIwMDksImV4cCI6MTY1OTc4MjMwOX0.VK7JCkRBw0mDCRbCBiJ2KIj5MO9th5WpukIiOqshpsA
Content-Type: application/json

###
POST http://localhost:4000/api/auth/refresh
Content-Type: application/json
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIiLCJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE2NjA3OTg5ODQsImV4cCI6MTY2MDgwMjU4NH0.ntaqPb_s-VxBxTHQyY40MYR_Pde4Vk4gfohO6SnQ44M

###
GET http://localhost:3500/accounts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIiLCJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE2NjAxMjM0ODIsImV4cCI6MTY2MDEyMzc4Mn0.vss7USi-WaEx1QPFRO7B78-PILz_fs0OAuz7AXqkF6U
Content-Type: application/json

###
POST http://localhost:3500/accounts/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIiLCJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE2NjAxMjM0ODIsImV4cCI6MTY2MDEyMzc4Mn0.vss7USi-WaEx1QPFRO7B78-PILz_fs0OAuz7AXqkF6U
Content-Type: application/json






